# Base image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

# Build image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy and restore dependencies
COPY ["E-Commerce/E-Commerce.csproj", "E-Commerce/"]
RUN dotnet restore "E-Commerce/E-Commerce.csproj"

# Copy all files and build the project
COPY . .
WORKDIR "/src/E-Commerce"
RUN dotnet build "E-Commerce.csproj" -c Release -o /app/build

# Publish the application
FROM build AS publish
RUN dotnet publish "E-Commerce.csproj" -c Release -o /app/publish

# Final image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "E-Commerce.dll"]
